# @package optimization
defaults:
  - model: attention_based_isolation_forest_sklearn
  - dataset: anomaly
  - logger: logger

report_path: "/home/dev/files/data/env/Attention-based-isolation-forest/atif/optimization_report.csv"