type_model:
  _target_: atif.models.AttentionBasedIsolationForestSklearn
  mode: 1

n_estimators: 150
seed: 1234 # 1430

attention_param:
  eps: 0.25 # contamination parameter
  softmax_tau: 0.8 # anomaly_score_threshold
  attention_sigma_threshold: 0.5

isolation_forest_param:
  offset: 0.3